name: MongoDB Backup

on:
  schedule:
    - cron: '0 13 * * *'   # 1:00 PM UTC every day
    - cron: '0 20 * * *'   # 8:00 PM UTC every day
  workflow_dispatch:   # Run manually too

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install MongoDB Tools
        run: |
          wget -q https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.9.0.tgz
          tar -xzf mongodb-database-tools-ubuntu2204-x86_64-100.9.0.tgz
          sudo mv mongodb-database-tools-ubuntu2204-x86_64-100.9.0/bin/* /usr/local/bin/
          mongodump --version

      - name: Run Backup Script
        env:
          PROD_MONGO_URI:            ${{ secrets.PROD_MONGO_URI }}
          BACKUP_MONGO_URI:          ${{ secrets.BACKUP_MONGO_URI }}
          CLOUDFLARE_ACCOUNT_ID:     ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_R2_TOKEN:       ${{ secrets.CLOUDFLARE_R2_TOKEN }}
          R2_BUCKET_NAME:            ${{ secrets.R2_BUCKET_NAME }}
        run: |
          chmod +x backup.sh
          ./backup.sh
