name: MongoDB Backup

on:
  schedule:
    - cron: '0 13 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install MongoDB Tools
        run: |
          wget -q https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.9.0.tgz
          tar -xzf mongodb-database-tools-ubuntu2204-x86_64-100.9.0.tgz
          sudo mv mongodb-database-tools-ubuntu2204-x86_64-100.9.0/bin/* /usr/local/bin/
          mongodump --version

      - name: Run Backup Script
        env:
          PROD_MONGO_URI: ${{ secrets.PROD_MONGO_URI }}
          BACKUP_MONGO_URI: ${{ secrets.BACKUP_MONGO_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: |
          chmod +x backup.sh
          ./backup.sh
